name: car_life
description: App to track your car lifetime
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  provider: ^6.0.5
  json_annotation: ^4.8.1
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_slidable: ^3.0.0
  amplify_flutter: ^0.6.13
  amplify_datastore: ^0.6.13
  amplify_api: ^0.6.13
  amplify_auth_cognito: ^0.6.13
  validators: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.4.4
  json_serializable: ^6.7.0
  lints: ^2.1.0

flutter:
  uses-material-design: false
  generate: true
